---
title: "Stream Gage Exploration"
author: "Juan De La Torre"
date: "November 5, 2024"
output: html_document.
---

This document was used to explore stream gages from USGS for Colorado, Wyoming,
Utah, and New Mexico.

```{r load dependencies}
library(tidyverse)
library(sf)
library(dataRetrieval)
library(nhdplusTools)
library(elevatr)
library(terra)
library(here)
library(mapview)


source(here("R", "nwis_functions.R"))
```

```{r filter states of interest}
states_oi <- c("Colorado") # "Wyoming", "Utah", "Kansas"
us_sf_object <- tigris::states() %>% 
  filter(NAME %in% states_oi) 
```

```{r NWIS sites}
# Get a list of NWIS sites for all of the states
nwis_sites_by_state <- map(us_sf_object$STUSPS, 
                           ~{
                             discharge_sites <- whatNWISsites(stateCd = .x, parameterCd = "00060") %>% 
                               filter(site_tp_cd == 'ST')
                             
                             small_enough <- readNWISsite(discharge_sites$site_no) %>%  
                               mutate(drain_area_km = drain_area_va *  2.58999) %>%  
                               filter(drain_area_km <= 1500)
                             
                             return(small_enough)
                             }
                           )

nwis_sites <- bind_rows(nwis_sites_by_state) 

# have to clean up the watersheds
```

```{r Watershed delineation from gages}
# Get watersheds associated with those stream gages
# nwis_watersheds <- pull(nwis_sites, site_no) %>% 
#   map_dfr(~nldi_finder(site_no = .)) %>% 
#   filter(!sf::st_is_empty(geometry)) %>% 
#   mutate(data = map(site_no, ~nldi_meta(site_no = .))) %>%
#   unnest(cols = c(data))
# Download data from those stream gages

# save those data so I don't have to keep calling that API
# saveRDS(nwis_watersheds, here('data', 'sf_files', 'nwis_watersheds.rds'))

# Read those data
nwis_watersheds <- read_rds(here('data', 'sf_files', 'nwis_watersheds.rds'))
```

```{r}
watershed_subset <- nwis_watersheds %>% 
  filter(site_no %in% nwis_sites$site_no) %>% 
  left_join(nwis_sites, by = "site_no") %>% 
  select(geometry, site_no, station_nm, drain_area_km)
mapview(watershed_subset)
```

```{r State elevation}
# get elevation for all of the sites
us_geo <- st_transform(us_sf_object, 4326)
elev_data <- get_elev_raster(us_geo, z = 7)
elev_terra <- rast(elev_data)
elev_points <- as.data.frame(elev_terra, xy = T)
names(elev_points)[3] <- "elevation"
```

```{r plot the sites with elevation}
# filter the objects for states of interest
filter_elev_points <- function(state = "Colorado") {
  # get elevation for all of the sites
  state_sf_object <- filter(us_sf_object, NAME == state)
  us_geo <<- st_transform(state_sf_object, 4326)
  elev_data <- get_elev_raster(us_geo, z = 7)
  elev_terra <- rast(elev_data)
  elev_points <- as.data.frame(elev_terra, xy = T)
  names(elev_points)[3] <- "elevation"
  return(elev_points)
}

filter_nwis_watersheds <- function(state = "Colorado") {
  state_sf_object <- filter(us_sf_object, NAME == state)
  state_code <- state_sf_object$GEOID
  
  # need to get nwis sites for the nwis watersheds
  filter_nwis_sites <- nwis_sites %>% 
    filter(state_cd == state_code) %>% 
    pull(site_no) %>% 
    unique(.)
  
  state_watersheds <- nwis_watersheds %>% 
    filter(site_no %in% filter_nwis_sites)
  
  return(state_watersheds)
}

elev_point_obj <- filter_elev_points()

filter_nwis_watersheds_obj <- filter_nwis_watersheds()

ggplot() +
  # Add elevation layer
  geom_raster(data = elev_point_obj,
              aes(x = x, y = y, fill = elevation)) +
  scale_fill_gradientn(
    colors = terrain.colors(10),
    name = "Elevation (m)") +
  # add outline of the current us_object
  geom_sf(data = us_geo,
          fill = NA,
          color = "black",
          size = 0.5) +
  # add nwis sites
  # geom_sf(data = st_transform(nwis_sites, 4326),
  #         color = "black",
  #         size = 1,
  #         alpha = 0.7) +
  # add watershed layer 
  geom_sf(
    data = filter_nwis_watersheds_obj,
    fill = NA,
    color = "blue"
  ) +
  # Customize the theme
  theme_minimal() +
  labs(title = "NWIS Sites in Colorado",
       subtitle = "With topographic relief") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "right") +
  coord_sf()

```

```{r}
sample_nwis_watersheds <- nwis_watersheds %>% 
  filter(st_geometry_type(geometry) == "POLYGON") %>%  
  slice_head(n = 5)
```

```{r}
# nhdplus high resolution (NHDPlus_HR used for this)
source(here("R", "nwis_functions.R"))

# try out the fetchNHD_flowlines function with the sample
test_fetch <- fetchNHD_flowlines(.data = sample_nwis_watersheds)

```

```{r}
mapview(test_fetch) + mapview(sample_nwis_watersheds)
```

