
```{r}
library(tidyverse)
library(dataRetrieval)
library(sf)
library(mapview)
library(nhdplusTools)
library(kableExtra)
library(here)
library(webshot)
source(here("R", "nwis_functions.R"))
```

```{r}
# Get a list of NWIS sites for Colorado
co_discharge_sites <- whatNWISsites(stateCd = "CO", parameterCd = "00060") %>% 
  filter(site_tp_cd == "ST") %>% 
  select(agency_cd, site_no, station_nm, dec_lat_va, dec_long_va) %>% 
  rowwise() %>% 
  mutate(gage_coords = st_sfc(st_point(x = c(dec_long_va, dec_lat_va)), crs = 4326)) 


# Read in watersheds for sites, and filter them for watersheds that have an area that is less than 1500km2
co_nwis_watersheds <- pull(co_discharge_sites, site_no) %>% 
  map_dfr(~nldi_finder(site_no = .)) %>% # this has a tryCatch that silences errors, need to put those gages somewhere
  filter(!sf::st_is_empty(geometry)) %>% 
  mutate(data = map(site_no, ~nldi_meta(site_no = .))) %>% # this has a tryCatch that silences errors as well
  unnest(cols = c(data)) %>% 
  filter(st_geometry_type(geometry) == "POLYGON",  # what about different geometry types?
         st_is_valid(geometry)) %>% 
  mutate(area = as.numeric(st_area(.)/1000000)) %>% 
  filter(area <= 1500) %>% 
  select(geometry, site_no, area) # removing the stats that came with these watersheds with this select
```

```{r}
# find the intersect of the watersheds and the points
site_watershed_intersect <- intersect(co_nwis_watersheds$site_no, co_discharge_sites$site_no)
```

```{r}
# each watershed is tied to one gage
filter_discharge_sites <- filter(co_discharge_sites, site_no %in% site_watershed_intersect)

filter_watersheds <- co_nwis_watersheds %>% 
  filter(site_no %in% site_watershed_intersect) %>%
  filter(as.character(st_geometry_type(.)) == "POLYGON")

# fetch flowlines for the first 5 watersheds
# This returns a list of dataframes for each flowline associated with a gage
test_flowline <- map(1:5, ~{
  watershed <- filter_watersheds[.x,]
  flowlines <- fetchNHD_flowlines(.data = watershed) %>% 
    mutate(natural = ifelse(ftype == 460, T, F),
           flowline_type = case_when(ftype == 460 ~ "natural",
                                     ftype == 558 ~ "artificial path",
                                     ftype == 468 ~ "drainageway",
                                     ftype == 336 ~ "canal ditch",
                                     ftype == 566 ~ "coastline",
                                     ftype == 334 ~ "connector",
                                     ftype == 428 ~ "pipeline",
                                     ftype == 420 ~ "underground conduit",
                                     .default = "unnatural")) 
  flowlines$site_no <- watershed$site_no
  return(flowlines)
}) %>%
  set_names(filter_watersheds$site_no[1:5])
```

```{r}
# Test intersection function solution with one watershed
# set sample site ID number
sample_site_no <- filter_discharge_sites$site_no[1]

# filter gages, watersheds, and flowlines for the relevant gage ID number
sample_site <- filter(filter_discharge_sites, site_no == sample_site_no)

sample_watershed <- filter(filter_watersheds, site_no == sample_site_no) %>% 
  st_cast("LINESTRING")

sample_flowline <- test_flowline[[sample_site_no]]

# Intersect the sample watershed and the sample flowlines to find intersections
sample_intersection_points <- st_intersection(sample_flowline, sample_watershed)

# Filter flowlines for those that intersect with the watershed boundary based on the flowline ID
sample_intersection_lines <- filter(sample_flowline, permanent_identifier %in% sample_intersection_points$permanent_identifier)

# map the example
mapview(sample_site$gage_coords) +
  mapview(sample_watershed) +
  mapview(sample_flowline, zcol = "flowline_type") +
  mapview(sample_intersection_points) +
  mapview(sample_intersection_lines)
```

```{r}
#' @params
#' gage_id = gage_id
#' point_list = list of gage points
#' polygon_list = list of watershed polygons
#' polyline_list = list of flowlines

# walk this function over the gage IDs, but the polygon list and polyline list needs to be supplied
watershed_candidate <- function(gage_id, point_list, polygon_list, polyline_list){
  
  gage_site <- filter(point_list, site_no == gage_id)
  
  gage_watershed_boundary <- st_cast(filter(polygon_list, site_no == gage_id), "LINESTRING")
  
  gage_flowlines <- polyline_list[[gage_id]]
  
  intersecting_flowline_points <- st_intersection(gage_flowlines, gage_watershed_boundary)

  # Which sub-flowlines intersect with these points and are they natural (I have a 'natural' bool column)
  
  intersecting_flowlines <- filter(gage_flowlines, permanent_identifier %in% intersecting_flowline_points$permanent_identifier)
  
  # here is where we split up the candidate sites!
  if (all(intersecting_flowlines$natural == TRUE) & nrow(intersecting_flowlines)<6){
    
    map <- mapview(gage_site$gage_coords, label = gage_id) +
      mapview(gage_watershed_boundary, label = "Watershed") +
      mapview(gage_flowlines, zcol = "flowline_type", lable = "Flowlines") +
      mapview(intersecting_flowline_points, color = 'red', label = "Intersecting Points") 
    
    mapshot(map, 
        url = here("data", "likely_natural", paste0(gage_id,".html")))
    
    cat('gage', gage_id, 'is likely natural\n')
    
  } else {
    
    map <- mapview(gage_site$gage_coords, label = gage_id) +
      mapview(gage_watershed_boundary, label = "Watershed") +
      mapview(gage_flowlines, zcol = "flowline_type", lable = "Flowlines") +
      mapview(intersecting_flowline_points, color = 'red', label = "Intersection Points") +
      mapview(intersecting_flowlines, color = 'red', label = "Intersecting Flowlines")
    
    mapshot(map, 
        url = here("data", "likely_unnatural", paste0(gage_id,".html")))
    
    cat('gage', gage_id, 'is likely unnatural\n')
    
  }
  
}
```

```{r}
# sample walk over the first 5 gages and relevant watersheds and flowlines
example_gages <- head(filter_discharge_sites, 5)

example_watersheds <- head(filter_watersheds, 5)

walk(example_gages$site_no, 
     ~suppressWarnings(watershed_candidate(gage_id = .x,
                          point_list = example_gages,
                          polygon_list = example_watersheds, # update these lists
                          polyline_list = test_flowline)))
```

